"""add bookmark table

Revision ID: 2e1a469b63ae
Revises: f19c069e798e
Create Date: 2026-09-02 21:53:15.840203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e1a469b63ae'
down_revision: Union[str, Sequence[str], None] = 'f19c069e798e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookmarks',
    sa.Column('bookmark_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.candidate_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['job_parameters.job_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('bookmark_id'),
    sa.UniqueConstraint('candidate_id', 'job_id', name='uq_candidate_job_bookmark')
    )
    op.create_index(op.f('ix_bookmarks_bookmark_id'), 'bookmarks', ['bookmark_id'], unique=False)
    op.create_index(op.f('ix_bookmarks_candidate_id'), 'bookmarks', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_bookmarks_job_id'), 'bookmarks', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookmarks_job_id'), table_name='bookmarks')
    op.drop_index(op.f('ix_bookmarks_candidate_id'), table_name='bookmarks')
    op.drop_index(op.f('ix_bookmarks_bookmark_id'), table_name='bookmarks')
    op.drop_table('bookmarks')
    # ### end Alembic commands ###
