"""create tables

Revision ID: 66c561035811
Revises: 
Create Date: 2026-08-26 14:27:48.900673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66c561035811'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('mobile_number', sa.String(length=15), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('candidate_id'),
    sa.UniqueConstraint('mobile_number')
    )
    op.create_index(op.f('ix_candidates_candidate_id'), 'candidates', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_candidates_email'), 'candidates', ['email'], unique=True)
    op.create_table('recruiters',
    sa.Column('recruiter_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('mobile_number', sa.String(length=15), nullable=False),
    sa.Column('organisation_email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('recruiter_id'),
    sa.UniqueConstraint('mobile_number')
    )
    op.create_index(op.f('ix_recruiters_organisation_email'), 'recruiters', ['organisation_email'], unique=True)
    op.create_index(op.f('ix_recruiters_recruiter_id'), 'recruiters', ['recruiter_id'], unique=False)
    op.create_table('candidate_details',
    sa.Column('candidate_details_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('education_qualification', sa.String(length=255), nullable=True),
    sa.Column('passedout_year', sa.Integer(), nullable=True),
    sa.Column('experience', sa.String(length=100), nullable=True),
    sa.Column('skills', sa.Text(), nullable=True),
    sa.Column('preferred_work_mode', sa.String(length=50), nullable=True),
    sa.Column('preferred_job_type', sa.String(length=50), nullable=True),
    sa.Column('preferred_work_location', sa.String(length=255), nullable=True),
    sa.Column('profile_picture', sa.String(length=500), nullable=True),
    sa.Column('resume', sa.String(length=500), nullable=True),
    sa.Column('github_url', sa.String(length=500), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.candidate_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('candidate_details_id')
    )
    op.create_index(op.f('ix_candidate_details_candidate_details_id'), 'candidate_details', ['candidate_details_id'], unique=False)
    op.create_index(op.f('ix_candidate_details_candidate_id'), 'candidate_details', ['candidate_id'], unique=True)
    op.create_table('job_parameters',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('recruiter_id', sa.Integer(), nullable=False),
    sa.Column('job_title', sa.String(length=150), nullable=False),
    sa.Column('required_skills', sa.String(length=1000), nullable=False),
    sa.Column('education_qualification', sa.String(length=255), nullable=False),
    sa.Column('experience', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('passedout_year', sa.Integer(), nullable=True),
    sa.Column('work_mode', sa.String(length=50), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('package', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['recruiter_id'], ['recruiters.recruiter_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_index(op.f('ix_job_parameters_job_id'), 'job_parameters', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_parameters_recruiter_id'), 'job_parameters', ['recruiter_id'], unique=False)
    op.create_table('job_descriptions',
    sa.Column('jd_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('generated_jd', sa.Text(), nullable=False),
    sa.Column('updated_jd', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job_parameters.job_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('jd_id')
    )
    op.create_index(op.f('ix_job_descriptions_jd_id'), 'job_descriptions', ['jd_id'], unique=False)
    op.create_index(op.f('ix_job_descriptions_job_id'), 'job_descriptions', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_descriptions_job_id'), table_name='job_descriptions')
    op.drop_index(op.f('ix_job_descriptions_jd_id'), table_name='job_descriptions')
    op.drop_table('job_descriptions')
    op.drop_index(op.f('ix_job_parameters_recruiter_id'), table_name='job_parameters')
    op.drop_index(op.f('ix_job_parameters_job_id'), table_name='job_parameters')
    op.drop_table('job_parameters')
    op.drop_index(op.f('ix_candidate_details_candidate_id'), table_name='candidate_details')
    op.drop_index(op.f('ix_candidate_details_candidate_details_id'), table_name='candidate_details')
    op.drop_table('candidate_details')
    op.drop_index(op.f('ix_recruiters_recruiter_id'), table_name='recruiters')
    op.drop_index(op.f('ix_recruiters_organisation_email'), table_name='recruiters')
    op.drop_table('recruiters')
    op.drop_index(op.f('ix_candidates_email'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_candidate_id'), table_name='candidates')
    op.drop_table('candidates')
    # ### end Alembic commands ###
