"""add jd version and publishing fields

Revision ID: f19c069e798e
Revises: 66c561035811
Create Date: 2026-08-26 19:39:12.757365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f19c069e798e'
down_revision: Union[str, Sequence[str], None] = '66c561035811'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_descriptions', sa.Column('version_number', sa.Integer(), nullable=False))
    op.add_column('job_descriptions', sa.Column('is_published', sa.Boolean(), nullable=False))
    op.add_column('job_descriptions', sa.Column('published_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_job_descriptions_is_published'), 'job_descriptions', ['is_published'], unique=False)
    op.create_unique_constraint('uq_job_description_version', 'job_descriptions', ['job_id', 'version_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_job_description_version', 'job_descriptions', type_='unique')
    op.drop_index(op.f('ix_job_descriptions_is_published'), table_name='job_descriptions')
    op.drop_column('job_descriptions', 'published_at')
    op.drop_column('job_descriptions', 'is_published')
    op.drop_column('job_descriptions', 'version_number')
    # ### end Alembic commands ###
